version: '3'

services:
  app:
    ports:
      - 80:80
    build: ./
    env_file: ./.env.production
    command: >
      sh -c "yarn build
      && yarn start"
    expose:
      - 80
    environment:
      PORT: 80
    volumes:
      - .:/app
